// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRAP0dnRB34ua3uIPjAcKQirpypRe-ig',
    appId: '1:976445872828:web:749ee679735cde4fcb4eb9',
    messagingSenderId: '976445872828',
    projectId: 'walkguide',
    authDomain: 'walkguide.firebaseapp.com',
    storageBucket: 'walkguide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmgRIaTjGCmteGhpdevV-UqF8dlrwZHCI',
    appId: '1:976445872828:android:7b140472f1465207cb4eb9',
    messagingSenderId: '976445872828',
    projectId: 'walkguide',
    storageBucket: 'walkguide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLAvHdRIw0G9UA4IkdI2veSDw0xSbg5g',
    appId: '1:976445872828:ios:1df522c79dec3405cb4eb9',
    messagingSenderId: '976445872828',
    projectId: 'walkguide',
    storageBucket: 'walkguide.firebasestorage.app',
    androidClientId:
        '976445872828-avpnlplcoh2v2bm8ahl9iieqb4r0clls.apps.googleusercontent.com',
    iosClientId:
        '976445872828-e4b5p5bb4io8b5fns8ojoc3r1prnev6u.apps.googleusercontent.com',
    iosBundleId: 'com.oss.walkGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLAvHdRIw0G9UA4IkdI2veSDw0xSbg5g',
    appId: '1:976445872828:ios:4ee3ee5062c2af36cb4eb9',
    messagingSenderId: '976445872828',
    projectId: 'walkguide',
    storageBucket: 'walkguide.firebasestorage.app',
    androidClientId:
        '976445872828-avpnlplcoh2v2bm8ahl9iieqb4r0clls.apps.googleusercontent.com',
    iosClientId:
        '976445872828-5ic6iudrec5qctq0ij3pqh0gknv5vb1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRAP0dnRB34ua3uIPjAcKQirpypRe-ig',
    appId: '1:976445872828:web:ba985f7f68056990cb4eb9',
    messagingSenderId: '976445872828',
    projectId: 'walkguide',
    authDomain: 'walkguide.firebaseapp.com',
    storageBucket: 'walkguide.firebasestorage.app',
  );
}
