name: walk_guide
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 기본 의존성
  cupertino_icons: ^1.0.8
  pedometer: ^4.1.1
  sensors_plus: ^6.1.1
  permission_handler: ^12.0.0+1

  # MLKit 및 카메라 관련 의존성 (추가됨)
  camera: ^0.10.5+9
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_commons: ^0.6.0
  isolate: '>=2.1.1 <4.0.0'


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

  # 음성 안내 기능 추가
  flutter_tts: ^3.8.2  
  fl_chart: ^0.71.0

  # firebase 로그인 기능용 패키지 추가
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
